test_format = 1.0

[default]

    args.enable_notify_push = "0"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.c5cf91ad.name = "Upgrade from 25.0.2"
    test_upgrade_from.caf917f3.name = "Upgrade from 26.0.2"
    test_upgrade_from.9c6d1eea.name = "Upgrade from 27.1.4"
    test_upgrade_from.980df89.name = "Upgrade from 28.0.10"
    test_upgrade_from.e9f82ab7.args.system_addressbook_exposed = "yes"

[notify_push_test]

    args.enable_notify_push = "1"
    test_upgrade_from.980df89.name = "Upgrade from 28.0.10"
    test_upgrade_from.e9f82ab7.args.system_addressbook_exposed = "yes"
    
